version: '3'
services:
  apache:
    build: .
    ports:
      - 80:80
      - 8080:8080
    volumes:
       - vol_persist:/var/www/data
    container_name: container_tp
volumes:
  vol_persist:

# Alternativas
# image: tvillani/tp_apache_server[:tag]
# - ./sitios/:/var/www/ 
