version: '3'
services:
  apache:
    build: .
    ports:
      - 80:80
      - 8080:8080
    volumes:
#      - ./:/var/www/html
       - vol_persist:/var/www/data 
volumes:
  vol_persist:

# Con pull dde dockerhub replace lin 4 c/: image: tvillani/tp_apache_server:tag
